### ISSUE TITLE
Forever 

### ISSUE THREAD

**Issue by gpicon6** [A-Georgiou/SimpleNikeAccountCreator#2]
npm install forever
npm WARN nike-bot@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ forever@0.15.3
updated 1 package and audited 1497 packages in 10.592s
found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by A-Georgiou** [comment]
Yeah this seems to be fine, when you run "npm start" does it begin using forever or does it run an error?

**Comment by gpicon6** [comment]
all good got it running, just to be clear, it wont always receive the sms right? i keep getting text not received

**Comment by A-Georgiou** [comment]
Yeah, if it doesnt receive the sms it wont take any money dont worry.
Nike has recently updated their system to block it from working after too many attempts (you will know you are blocked when you just dont receive the texts anymore) so I have just added single proxy support to help if you get blocked and im in the process of letting it handle proxy lists and just running through the list changing to the next proxy each time you are banned on the previous

**Comment by gpicon6** [comment]
got it thanks

**Comment by gpicon6** [comment]
do you recommend datacenter proxies or residential?

**Comment by A-Georgiou** [comment]
for this type of process definitely datacenter proxies for both cost and the fact you find a huge number of residential proxies are just datacenter proxies sold as being residential
